export default {  
  
  // Actions

  ALL_BROADBAND_LIST_REQUEST: 'all-broadband:ALL_BROADBAND_LIST_REQUEST',  
  ALL_BROADBAND_LIST_SUCCESS: 'all-broadband:ALL_BROADBAND_LIST_SUCCESS',  
  ALL_BROADBAND_LIST_FAILURE: 'all-broadband:ALL_BROADBAND_LIST_FAILURE'
  
};

